language: ruby
sudo: false
rvm:
  - 2.3.3

cache: bundler

install:
  - gem install ascii_binder
  - gem pristine --all
  - pip install -r requirements.txt
  - python setup.py install

after_install: gem list

script:
  - flake8 --max-line-length=100

after_success:
  - bash scripts/build_docs.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: https://github.com/smitthakkar96/fedora_docs_proposal
  local_dir: fedora_docs_proposal/_package/main
  on:
    branch: master
