language: python

dist: precise

sudo: true

python:
  - "3.6"

cache: bundler

before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.3

install:

  - sudo gem install ascii_binder
  - sudo pip3 install -r requirements.txt
  - python setup.py install

script:
  - flake8 --max-line-length=100

after_success:
  - bash scripts/build_docs.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: https://github.com/smitthakkar96/fedora_docs_proposal
  local_dir: fedora_docs_proposal/_package/main
  on:
    branch: master
